import fs from "fs";
import path from "path";
import { GetStaticPaths, GetStaticProps } from "next";
import { sanityFetch } from "../../lib/sanity";
import TrailHomeDetailClient from "../../components/TrailHomeDetailClient";
import Head from "next/head";

// Copy this from TrailHomeDetailClient
type GalleryImage = { url: string };

type HandpickedHome = {
  _id: string;
  address: string;
  price: number;
  beds: number;
  baths: number;
  squareFeet: number;
  acreage: string;
  description?: string;
  gallery: GalleryImage[];
  trailName?: string;
  distanceToTrail?: number;
  rideWithGPSID?: string;
  listingAgent?: string;
  date?: string;
};

export const getStaticPaths: GetStaticPaths = async () => {
  try {
    // Read the static params file generated by the script
    const staticParamsPath = path.join(process.cwd(), "static-params.json");
    
    if (!fs.existsSync(staticParamsPath)) {
      console.warn("static-params.json not found, using empty paths array");
      return { paths: [], fallback: false };
    }
    
    const staticParams = JSON.parse(fs.readFileSync(staticParamsPath, "utf-8"));
    console.log(`Found ${staticParams.length} static paths to generate`);

    // Map the params to the format Next.js expects
    const paths = staticParams.map(({ slug }: { slug: string }) => ({
      params: { slug },
    }));

    return { 
      paths, 
      fallback: false // Return 404 for any paths not included in paths
    };
  } catch (error) {
    console.error("Error reading static params:", error);
    return { paths: [], fallback: false };
  }
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  try {
    const slug = params?.slug;

    if (!slug) {
      return { notFound: true };
    }

    // Create a fallback home if needed for build
    const fallbackHome = {
      _id: "fallback",
      address: `${slug}`,
      price: 0,
      beds: 0,
      baths: 0,
      squareFeet: 0,
      acreage: "0",
      description: "Details coming soon",
      gallery: [{ url: "/fallback-image.jpg" }],
      trailName: "Unknown Trail",
      distanceToTrail: 0,
      rideWithGPSID: "0",
      listingAgent: "Jenna Gragg"
    };

    try {
      // Fetch the home data from Sanity
      const query = `
        *[_type == "handpick" && slug.current == "${slug}"][0]{
          _id,address,price,beds,baths,squareFeet,acreage,description,
          "gallery": gallery[]{ "url": asset->url },
          trailName,distanceToTrail,rideWithGPSID,listingAgent
        }
      `;
      
      const home = await sanityFetch(query);

      if (!home) {
        console.warn(`No data found for slug: ${slug}, using fallback home data`);
        return {
          props: { 
            home: fallbackHome,
            slug
          }
        };
      }

      // Return the home data as props
      return {
        props: { 
          home,
          slug // Include the slug in props for future reference
        }
      };
    } catch (error) {
      console.error(`Error fetching home data for ${slug}:`, error);
      return {
        props: { 
          home: fallbackHome,
          slug
        }
      };
    }
  } catch (error) {
    console.error("Error in getStaticProps:", error);
    return { notFound: true };
  }
};

export default function TrailHomeDetailPage({ home }: { home: HandpickedHome }) {
  return (
    <>
      <Head>
        <title>{home.address} | Trail Homes</title>
        <meta name="description" content={`${home.address} - ${home.beds} beds, ${home.baths} baths, ${home.squareFeet} sq ft`} />
      </Head>
      <TrailHomeDetailClient home={home} />
    </>
  );
}